OSG/OSG/Controllers/ForumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Services.Description;
using OSG.Models;

namespace OSG.Controllers
{
    public class ForumController : Controller
    {
        //
        // GET: /Forum/

        private static List<ForumTopic> topics = new List<ForumTopic>
        {
            new ForumTopic
            {
                Message = "Bugs Everywhere",
                Title = "IT",
                SubTopics = new List<ForumTopic>
                {
                    new ForumTopic
                    {
                        Title = "Gaming Crisis",
                        Message = "I hate buggy games",
                        Posts =
                            new List<ForumPost>
                            {
                                new ForumPost
                                {
                                    Message = "Hate Bugs",
                                    SubPosts = new List<ForumPost> {new ForumPost {Message = "Me Too"}}
                                }
                            }
                    }
                },

            },
            

            new ForumTopic
            {
                Message = "Brain Storming At Its Finest",
                Title = "Game Ideas",
                SubTopics = new List<ForumTopic>
                {
                    new ForumTopic
                    {
                        Title = "Happy Land",
                        Message = "Floating with the best of them",
                        Posts =
                            new List<ForumPost>
                            {
                                new ForumPost
                                {
                                    Message = "Loving it",
                                    SubPosts = new List<ForumPost> {new ForumPost {Message = "Me Too"}}
                                }
                            }
                    }
                },

            }
        };
            


        public ActionResult Index()
        {
            return View("ForumIndex", topics);
        }


        public ForumTopic FindTopic(IEnumerable<ForumTopic> topicList ,int id)
        {
            ForumTopic foundTopic = null;
            if(topicList.Any())
            foreach (var topic in topicList)
            {
                if (topic.Id == id)
                {
                    foundTopic = topic;
                    break;
                }
                if (topic.SubTopics.Any())
                {
                    foundTopic = FindTopic(topic.SubTopics, id);
                    if (foundTopic != null)
                    {
                        break;
                    }
                }
            }

            return foundTopic;
        }

        public ActionResult DisplayPosts(int mainTopicId)
        {
            ForumTopic topic = topics.FirstOrDefault(p => p.Id == mainTopicId) ?? FindTopic(topics,mainTopicId);


            List<ForumPost> posts = null;//topic.Posts;
            if (topic != null)
            {
                posts = topic.Posts;
                ViewBag.PanelTitle = topic.Title;
            }
            return View("DisplayPosts", posts);
        }

        public ActionResult DisplaySubTopics(int mainTopicId)
        {
            return View("DisplaySubTopics", topics.FirstOrDefault(t=>t.Id == mainTopicId));
        }
    }
}

OSG/OSG/Views/Shared/Partial/_GameDetails.cshtml
@model OSG.Models.Game
<div>

    <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseGameDetials">Game Details
                    </a>
                </h3>
            </div>
        <div id="collapseGameDetials" class="panel-collapse collapse">
            <div class="panel-body">
                <div class="gamesDetials">
                    <p>Title : @Model.Title</p>
                    <p>
                        Rating : 
                        @{
                            //int rating = (int)@Model.Rating;
                            for (int i = 0; i < ((int)Model.Rating); i++)
                             {
                                 <span class="glyphicon glyphicon-star"></span>
                             }
                        }
                    </p>
                    <p>Release Date : @Model.ReleaseDate</p>
                    <p>Play Count : @Model.PlayCount</p>
                    <p>
                        Tags :
                        @foreach (var t in @Model.Tags)
                        {
                            <span class="gameTag">@t </span>
                        }
                    </p>

                </div>
            </div>
        </div>
    </div>
</div>

OSG/OSG/Views/Shared/Partial/_GamePartial.cshtml
@model OSG.Models.Game

<div class="singleGame">
    <div>
        <a class="gameLink" href=@Url.Action("DisplayGame","Home",new {gameId = @Model.Id})>
            @Model.Title
        </a>
    </div>
    <img class="gameImage" />
    <div>
        @for (int i = 0; i < ((int)Model.Rating); i++)
        {
            <span class="glyphicon glyphicon-star"></span>
        }
    </div>
</div>

OSG/OSG/Views/Shared/Partial/_GamesPartial.cshtml
@model IEnumerable<OSG.Models.Game>

<div>

    <div class="panel panel-default">
        <div class="panel-heading">
   
            <h2><a href=@Url.Action(@ViewBag.Link,"Home") class="gamePanelLink">@ViewBag.PanelTitle</a></h2>
        </div>
        <div class="panel-body" >
            <div class="gamesList">
                
                @foreach(var g in @Model){
                    Html.RenderPartial("Partial/_GamePartial",g);
                }
            </div>
        </div>
    </div>
</div>

OSG/OSG/Views/Shared/Partial/_MainTopicPartial.cshtml
@using OSG.Models
@model OSG.Models.ForumTopic

<div>
    <h3>
        @if (@Model.SubTopics.Any())
        {
            <a class="forumTopic" href=@Url.Action("DisplaySubTopics", "Forum", new {mainTopicId = @Model.Id})>@Model.Title</a>
        }
        else
        {
            <a class="forumTopic" href=@Url.Action("DisplayPosts", "Forum", new {mainTopicId = @Model.Id})>@Model.Title</a>
        }
        
    </h3>
    <p>@Model.Message</p>
</div>

OSG/OSG/Views/Shared/Partial/_MainTopicsPartial.cshtml
@model IEnumerable<OSG.Models.ForumTopic>

<div>
    <div class="panel panel-default">
        <div class="panel-heading">   
            <h2>@ViewBag.PanelTitle</h2>
        </div>
        <div class="panel-body" >
            @foreach (var topic in @Model)
            {
                Html.RenderPartial("Partial/_MainTopicPartial",topic);
            }
        </div>
    </div>
</div>

OSG/OSG/Views/Shared/Partial/_PostsPartial.cshtml
@model OSG.Models.ForumPost


<div class="panel panel-default">
  <div class="panel-body">
      @Model.Message;
      @{Html.RenderPartial("Partial/_SubTopicsPartial", @Model.SubPosts);}
  </div>
</div>

OSG/OSG/Views/Shared/Partial/_SubTopicsPartial.cshtml
@model IEnumerable<OSG.Models.ForumPost>

@if (@Model != null)
{
    foreach (var post in @Model)
    {

        <div class="panel panel-default">
            <div class="panel-body">
                @post.Message
                @{ Html.RenderPartial("Partial/_SubTopicsPartial", post.SubPosts); }
            </div>
        </div>
    }
}