ColtersAchievementProject/ProjectOSG/Models/Game.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ProjectOSG.Models
{
    [Table("Games")]
    public partial class Game
    {
        private static float FEATURED_RATING = 4.7f;
        private static float FEATURED_MONTHS_MAX = 3;
        private static float FEATURED_MONTHS_MIN = 1;

        [Key]
        public int Id { get; set; }
        [Required]
        public string Title { get; set; }
        [Required]
        public DateTime ReleaseDate { get; set; }

        [Required]
        public double Rating { get; set; }

        [Required]
        public int NumberOfRatings { get; set; }

        [Required]
        public int PlayCount { get; set; }

        [Required]
        public string Instructions { get; set; }

        [Required]
        public string URL { get; set; }

        public bool Featured
        {
            get
            {
                int numberOfMonths =ReleaseDate.Month - DateTime.Today.Month;
                return (ReleaseDate.Year == DateTime.Today.Year && Rating >= FEATURED_RATING &&
                        numberOfMonths >= FEATURED_MONTHS_MIN && numberOfMonths <= FEATURED_MONTHS_MAX );
            }
        }
    }
}

ColtersAchievementProject/ProjectOSG/Controllers/GameController.cs
using ProjectOSG.Models;
using ProjectOSG.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjectOSG.ViewModel;
namespace ProjectOSG.Controllers
{
    public class GameController : Controller
    {
        //
        // GET: /Game/
        static GameRepository GR = new GameRepository();

        public ActionResult Index()
        {
            List<GameVM> GVM = new List<GameVM>();

            foreach (var VM in GR.All())
            {
                GameVM temp=new GameVM();
                temp.gameID = VM.Id;
                temp.rating = VM.Rating;
                temp.releaseDate = VM.ReleaseDate;
                temp.Title = VM.Title;

                GVM.Add(temp);
            }

            return View(GVM);
        }
        public ActionResult SingleGame(GameVM singleGame)
        {
            return View(singleGame);
        }
       

        public ActionResult Display(int gameId)
        {
            GameRepository games = new GameRepository();
            return View(games.Find(gameId));
        }

        public ActionResult DisplayTagged(Tag tag)
        {
            ViewBag.Title = tag.ToString();
            ViewBag.PanelTitle = tag.ToString();
            //List<GameVM> tagGames = TheGames.Where(g => g.Tags.Contains(tag.ToString())).ToList();
           
            return View("Index",GR.All());
        }

        public ActionResult MostPlayed()
        {
            GameRepository games = new GameRepository();

            ViewBag.Title = "MostPlayed";
            ViewBag.PanelTitle = "Most Played";
            return View("AllGames", GR.All().OrderByDescending(g => g.PlayCount));
        }

        public ActionResult TopRated()
        {
            GameRepository games = new GameRepository();

            ViewBag.Title = "TopRated";
            ViewBag.PanelTitle = "Top Rated";
            return View("AllGames", GR.All().OrderByDescending(g => g.Rating));
        }

        public ActionResult NewGames()
        {
            GameRepository games = new GameRepository();

            ViewBag.Title = "NewGames";
            ViewBag.PanelTitle = "New Games";
            return View("AllGames", GR.All().OrderByDescending(g => g.ReleaseDate));
        }


        [HttpPost]
        public ActionResult SearchGames()
        {
            IEnumerable<ProjectOSG.Models.Game> gamesReturned = null;
            string title = Request.Params["gameTitle"];
            GameRepository games = new GameRepository();

            if (title != null)
            {
                ViewBag.Link = "Index";
                ViewBag.PanelTitle = "Games Found";
                gamesReturned = games.All().Where(g => g.Title.ToLower().Contains(title.ToLower().Trim()));
            }

            return (gamesReturned == null) ? View("GameNotFound") : View("AllGames", gamesReturned);
        }
        [HttpGet]
        public ActionResult AddGame()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddGame(GameVM gvm)
        {
           //GR.Insert(gvm);
            return View("SingleGame",gvm);
        }
        [HttpGet]
        public ActionResult EdditGame(string Title)
        {
            var result = GR.All().Where(m => m.Title == Title).FirstOrDefault();
            return View("AddGame",result);
        }
        [HttpPost]
        public ActionResult EdditGame(GameVM gvm)
        {
            //GR.Update(gvm);
            return View("SingleGames",gvm);
        }

        static public IEnumerable<Game> getAllGames()
        {
            return GR.All();
        }
    }
}

ColtersAchievementProject/ProjectOSG/Views/Game/AddGame.cshtml
@using ProjectOSG.Controllers;
@model ProjectOSG.ViewModel.GameVM

@{
    ViewBag.Title = "AddGame";
    Layout = "~/Views/Shared/Layout/_MainLayout.cshtml";
}
<script src="~/Scripts/MoveItemButtons.js" type="text/javascript" ></script>
<h2>AddGame</h2>
     @{
         List<string> tagTypes = TagController.GrabAllTags().ToList();

         List<string> empty = new List<string>();
        
         SelectList sl = new SelectList(tagTypes);
         SelectList chosenSL = new SelectList(empty);
         
            }
     @if (Model == null)
     {

         using (Html.BeginForm())
         {
            
         
           <ul>
               <li>
                @Html.LabelFor(m => m.Title)<br />
           @Html.TextBoxFor(m => m.Title)
             </li>
               <li>
              @Html.LabelFor(m => m.creater)<br />
             @Html.TextBoxFor(m => m.creater)
          </li>
               <li>
              @Html.LabelFor(m => m.description)<br />
             @Html.TextAreaFor(m => m.description)
      </li>
               <li>
              @Html.LabelFor(m => m.rating)<br />
             @Html.TextBoxFor(m => m.rating)

               </li>
               <li>
              @Html.LabelFor(m => m.releaseDate)<br />
           @Html.TextBoxFor(m => m.releaseDate)
            </li>
           </ul>
        
             @Html.Label("Chosen") <span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>  @Html.Label("Not Chosen")<br />
             @Html.ListBoxFor(m => m.Tags, chosenSL, new { @multiple = "multiple" })
         
            <input type="button" onclick="move(this.form.Tags, this.form.Not_Chosen)
            
                 " value="->" />
            <input type="button" onclick="move(this.form.Not_Chosen, this.form.Tags)" value="<-" />
               
            @Html.ListBox("Not Chosen", sl)<br />
         <br />
         <p>select chosen ones before adding game</p>
           <span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>  <input type="submit" value="AddGame" />
         
           
         }
     }
     
   @*  else
     {
         using (Html.BeginForm())
         {

             chosenSL = new SelectList(Model.Tags);
             <ul>
               <li>
                @Html.LabelFor(m => m.Title)<br />
           @Html.TextBoxFor(m => m.Title)
             </li>
               <li>
              @Html.LabelFor(m => m.creater)<br />
             @Html.TextBoxFor(m => m.creater)
          </li>
               <li>
              @Html.LabelFor(m => m.description)<br />
             @Html.TextAreaFor(m => m.description)
      </li>
               <li>
              @Html.LabelFor(m => m.rating)<br />
             @Html.TextBoxFor(m => m.rating)

               </li>
               <li>
              @Html.LabelFor(m => m.releaseDate)<br />
           @Html.TextBoxFor(m => m.releaseDate)
            </li>
           </ul>
             @Html.Label("Chosen") <span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>  @Html.Label("Not Chosen")<br />
             @Html.DropDownListFor(m => m.Tags, chosenSL, new { @multiple = "multiple" })
            <input type="button" onclick="move(this.form.Tags, this.form.Not_Chosen)" value="->" />
            <input type="button" onclick="move(this.form.Not_Chosen, this.form.Tags)" value="<-" />
               
            @Html.ListBox("Not Chosen", sl)<br />

         <br />
             <input type="submit" value="Edit Game" />
         }
     }*@
    
         

ColtersAchievementProject/ProjectOSG/Views/Game/Index.cshtml
@using ProjectOSG.ViewModel
@using ProjectOSG.Controllers

@model IEnumerable<GameVM>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout/_MainLayout.cshtml";
}

<h2>Index</h2>
@if(Model!=null){
foreach (GameVM item in Model)
{
     
   <div id="singleGame2" >
    Title <br /><h3>@Html.ActionLink(item.Title, "SingleGame", "Game", item, null)
    <br /><p>  @item.releaseDate</p>  
     <div>
        @for (int i = 0; i < ((int)item.rating); i++)
        {
            <span class="glyphicon glyphicon-star"></span>
        }
    </div>
    @if(item.creater!=null)
    {
     <p>Created by @item.creater</p>
    }
    else
    {
        <p>Created by Unknown</p>
    }
     <p>Description <br /> @item.description</p>
    <p>Tags:</p>
    @if(GameTagController.GetTagsBelongingToGame(item.gameID)!=null){
        foreach (var item2 in GameTagController.GetTagsBelongingToGame(item.gameID))
    {
        <p>@item2.TagType</p>
    }
    
   
  }
  </div>
}
}

ColtersAchievementProject/ProjectOSG/Views/Game/SingleGame.cshtml
@model ProjectOSG.ViewModel.GameVM

@{
    ViewBag.Title = "SingleGame";
    Layout = "~/Views/Shared/Layout/_MainLayout.cshtml";
}
@*@section Edit
{
     <li>
        @Html.ActionLink("Edit Game", "EditGame", "Game",@Model.Title);
     </li> 
    }*@
<h2>SingleGame</h2>
@{ Html.RenderPartial("Partial/_GameVM", @Model); }